#%RAML 1.0
title: SysAPI

types:
  accountType: !include /datatypes/AccountType.raml
  account: !include /datatypes/Account.raml

/accounts:
  get:
    description: Retreive account info
    headers:
      id:
        type: integer
    queryParameters:
      accountType:
        type: string
        required: false
      account:
        type: string
        required: false

    responses:
      200:
        body:
          application/json:
            items: account
            examples:
              output: !include /examples/Accounts.raml
      404:
        body:
          application/json:
            examples:
              message: Account not found

  post:
    description: Create a new account
    headers:
      id:
        type: integer
    body:
      application/json:
        type: array
        items: account
        examples:
          input: !include /examples/AccountsPost.raml

    responses:
      201:
        body:
          application/json:
            example:
              message: Account added
      409:
        body:
          application/json:
            example:
              message: Account already exists.

