#%RAML 1.0
title: SysAPI

types:
  AccountType: !include /datatypes/AccountType.raml
  account: !include /datatypes/Account.raml

/accounts:
  get:
    headers:
      user-id:
    queryParameters:
      enum:
        examples:
          AccountType: 