#%RAML 1.0
title: SysAPI

types:
  AccountType: !include /datatypes/AccountType.raml
  Account: !include /datatypes/Account.raml

/accounts:
  get:
    headers:
      user-id:
    queryParameters:
      Account_Type:
        type: AccountType
        required: True
      Account_Name:
        type: Account
        required: True
    responses:
      200:
        body:
          application/json:
            items: Account
            examples:
              output: !include /examples/Accounts.raml
      

