#%RAML 1.0
title: SysAPI

types:
  AccountType: !include /datatypes/AccountType.raml
  account: !include /datatypes/Account.raml

/accounts:
  get:
    description: Collects accounts
    headers:
      User
